# Generated by Django 3.0 on 2019-12-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('elo_rating', models.IntegerField()),
                ('total_games_count', models.IntegerField()),
                ('complete_games_count', models.IntegerField()),
            ],
        ),
    ]
